### ISSUE TITLE
Timezone issue

### ISSUE THREAD

**Issue by avolent** [avolent/net-test#1]
Either allow users to set their own timezone or find a way to make sure it is correct and not always UTC

**Comment by Airz0** [comment]
Sydney and Melbourne share the same timezone (UTC/GMT+11) even though they're 1 hour apart, if you search UTC+11 time it'll give Melbourne time but GMT+11 gives Sydney time

**Comment by avolent** [comment]
Fixed in [82571d0](https://github.com/avolent/net-test/commit/82571d09e743bcdd471cb835c6fa9711828fdc5f)
Updated docker-compose.yaml linking host time to container time.
Host time needs to be correct for container time to reflect.
